UoaWDCC/nzpmc_frontend

src/components/AnswerList.vue, src/views/Login.vue, src/views/Welcome.vue
**Issue**
Student needs to go from one page to another
**Solution**
added redirects using router.push()
**Risk**
None
**Reviewers**
=> [NZPMC 007] Connected different pages with redirects

src/App.vue, src/components/AnswerList.vue, src/views/Exam.vue
**Issue**
The exam page needs a layout for the components
**Solution**
Implemented the exam page layout with v-sheets as placeholders
**Risk**
Layout margins/paddings may need adjustments once components are completed.
**Reviewers**
=> [NZPMC 020] Added Exampage layout

src/components/AnswerList.vue, src/components/Sidebar.vue, src/components/SingleAnswer.vue, src/components/SingleQuestion.vue, src/components/Topbar.vue, src/views/Exam.vue
**Issue**
NZPMC-030 and NZPMC-032
Sidebar displayed in the wrong position when window refreshed, question image sizes are too small, question number not displayed correctly, option box sizes
**Solution**
Overwrote Vuetify code trying to do its own thing, for our own custom use, updated timer to work in hours, used flex stretch property to make everything the same height and used the index of everything in the sidebar to update the question number for each question view.
**Risk**
None known.
**Reviewers**
@scorpionknifes @Will-ZYS @Kingston802 @ruby-oujo
=> Nzpmc 030/single question display

src/components/AnswerList.vue, src/components/SingleAnswer.vue, src/components/SingleQuestion.vue, src/gql/queries/userQuiz.js, src/views/Exam.vue
**Issue**
mutation was not being used to change the user's selection answer
**Solution**
User's selected option is now being updated using the Apollo mutation
**Risk**
None known
**Reviewers**
@Will-ZYS 
@matthewaptaylor 
@ruby-oujo 
@danieltorrey
=> Nzpmc 031/integrate user select option query

package-lock.json, package.json, src/components/AnswerList.vue, src/components/Sidebar.vue, src/views/Exam.vue, vue.config.js
previous and next buttons are functioning; also the sidebar is updated to follow the changes of questions.
**Risk**
exam page as well as sidebar component had to be updated to allow for these changes 
**Reviewers**
@Will-ZYS  @matthewaptaylor
=> Nzpmc 036/implemenet next prev submit button

src/components/Sidebar.vue, src/components/SingleQuestion.vue, src/components/SubmissionConfirmation.vue, src/views/Exam.vue, src/views/Login.vue
**Issue**
Did not have loading messages for logging in and exam questions
**Solution**
Implemented loading messages for logging in and exam questions
**Risk**
No risk
**Reviewers**
=> [NZPMC-035] Added loading and connection error messages to components

src/components/AnswerList.vue, src/components/SingleQuestion.vue, src/components/SubmissionConfirmation.vue, src/components/Topbar.vue, src/main.js, src/views/Exam.vue, src/vue-apollo.js
**Issue**
Fixes mobile support issues and login bug
**Solution**
Next button will no longer go out of frame on a mobile device, menu closes when clicked.
Whenever a token will expire within 10 seconds, or has expired, and a request to GraphQL is made, Apollo will first check if a new token exists, and if it does, put it into local storage.
**Risk**
None known
=> Nzpmc 047/mobile support buttons

src/components/AdminTopbar.vue, src/components/QuizAdminDetails.vue, src/components/QuizAdminQuestion.vue, src/components/QuizAdminSidebar.vue, src/components/QuizAdminUsers.vue, src/components/SignOutMenu.vue, src/components/Topbar.vue, src/router/index.js, src/views/QuizAdmin.vue, src/views/UserAdmin.vue, src/vue-apollo.js
**Issue**
About to start development of an admin page
**Solution**
Added topbar for navigation, setup blank components to be coded once design finalised.
**Risk**
None known
=> Admin page set up

src/components/UserSearchBar.vue
**Issue**
Colour was wrong 
**Solution**
Changed the colour
**Reviewers**
=> Changed colour of searchbar

package-lock.json, src/gql/mutations/userQuiz.js, src/gql/queries/option.js, src/gql/queries/question.js, src/gql/queries/userQuiz.js, src/router/index.js, src/views/Exam.vue, src/views/Welcome.vue
**Issue**
Query multiple userQuiz, Query one userQuiz, Add page for viewing multiple userQuiz
**Solution**
Implemented multiple additional buttons for start and continue / continue to start / start to continue with  multiple colours 
**Risk**
Made changes to welcome page and exam page and also apollo mutations  
**Reviewers**
@scorpionknifes  @Will-ZYS  @lanxdrey19
=> [NZPMC-070] select from userquizzes

src/components/AdminTopbar.vue, src/components/QuizAdminSidebar.vue, src/components/QuizAdminSingleAnswer.vue, src/gql/fragments/adminQuiz.js, src/gql/mutations/adminQuiz.js, src/gql/queries/adminQuiz.js, src/views/QuizAdmin.vue, src/views/QuizAdminDetails.vue, src/views/QuizAdminQuestion.vue
**Issue**
QuizAdmin page didn't work
**Solution**
Connect to backend
**Reviewers**
=> Nzpmc 063/connect quizadmin page

src/components/Welcome.vue
**Issue**
Better video
**Solution**
Change video
=> Added Rick roll to welcome

src/components/Quiz/QuizTopbar.vue
**Issue**
Font Sizing 
**Solution**
Changed to bold
=> ✨ Changed the time remaining font

src/components/Welcome.vue
**Issue**
Outdated welcome text.
**Solution**
Fix
**Risk**
Time travel
**Reviewers**
=> 🐛 Changed year on welcome page

package-lock.json, package.json, src/components/Admin/Admin.vue, src/components/Admin/AdminTopbar.vue, src/components/Admin/Quiz/QuizAdmin.vue, src/components/Admin/Quiz/QuizAdminDetails.vue, src/components/Admin/Quiz/QuizAdminEditor.vue, src/components/Admin/Quiz/QuizAdminLatexDialog.vue, src/components/Admin/Quiz/QuizAdminOption.vue, src/components/Admin/Quiz/QuizAdminQuestion.vue, src/components/Admin/Quiz/QuizAdminSidebar.vue, src/components/DisplayText.vue, src/components/Quiz/Quiz.vue, src/components/Quiz/QuizAnswer.vue, src/components/Quiz/QuizQuestion.vue, src/components/Quiz/QuizTopbar.vue, src/gql/mutations/adminQuiz.js
**Issue**
Buggy admin page, not all functions connected to backend
**Solution**
Fix bugs, create GraphQL queries/mutations and connect to prewritten variables
**Reviewers**
=> Nzpmc 064/connect quizadminquestion

src/components/Welcome.vue
**Issue**
Video is no longer needed, so we can place the quiz list to where the video was originally at
**Solution**
Moves list of quiz from inside the dialog to outside and deletes dialog.
**Risk**
* `Welcome.vue` may contain some deprecated code
=> Move contents of dialog to card

src/components/Admin/Quiz/QuizAdminQuestion.vue
**Issue**
The answer shows up again in the other options
**Solution**
Created a method to filter out the answer option without needing to change the actual options array.
**Reviewers**
@matthewaptaylor @p4ckysm4cky @scorpionknifes
=> [NZPMC-094] 🐛 Fixed the answer showing the other options

src/components/Admin/Quiz/QuizAdminSidebar.vue, src/components/Admin/Quiz/QuizAdminSidebarReorder.vue, src/gql/mutations/questions.js
**Issue**
We needed to add question reordering to the question sidebar
**Risk**
* caching causing questions to not refresh
=> [NZPMC-091]/question ordering

src/components/Quiz/QuizSidebar.vue
**Issue**
Submit button wasn't at the bottom 
**Solution**
Fixed
=> 💄 Moved submit button to the bottom

firebase.json, package-lock.json, package.json, src/components/DisplayText.vue
**Issue**
Certain questions would not properly render on the site, because of conflict in syntax when using markdown alongside LaTeX
**Solution**
Find common characters in markdown that are in LaTeX math blocks and escape them before they are converted into HTML using showdown
**Discussion**
The LaTeX component used in the project was switched for KaTeX, since it seems to provide a more consistent look compared to before.
**Risk**
Since the original LaTeX component is no longer used. It is now using `v-html`, which could be a potential XSS issue. However, since editing questions can only be done in the admin dashboard it should be fine (?).
**Reviewers**
=> [NZPMC-092]/LaTeX not rendering

firebase.json, package-lock.json, src/components/Admin/User/UserAdmin.vue, src/components/Admin/User/UserAdminDetails.vue, src/gql/fragments/user.js, src/gql/mutations/user.js, src/gql/queries/user.js
**Issue**
UserAdmin view has not been implemented
**Solution**
Implement UserAdmin view using Vuetify datatable to display a paginated list of users. The datatable also supports searching of the users. 
Limit is set to 5 to show that pagination works. When there are more users in the database, set this to 50
**Risk**
n/a
**Reviewers**
=> [NZPMC-060] Implement UserDisplay component and UserAdmin view

src/components/Admin/Quiz/QuizAdminOption.vue, src/components/Admin/Quiz/QuizAdminQuestion.vue, src/gql/mutations/adminQuiz.js, src/gql/queries/time.js
**Issue**
No functionality to delete question and answer.
**Solution**
Added delete buttons for questions and answers. Does a check for the current time if it's between the test time to prevent deletion. 
**Reviewers**
=> Nzpmc 093/delete answers and questions

package-lock.json, src/components/App/Exam/FinishedDialog.vue, src/components/App/Exam/TopbarTimer.vue
**Issue**
- When the timer reaches 0 seconds, nothing will occur
**Solution**
- A dialog shows up when the timer reaches the value 0. This dialog will contain a submit button and it will indicate to the user that they need to click it.
- The user cannot click out of the dialog (in the attempt to change their answer)
- On clicking the submit button of the dialog, it will direct them to the submission page
**Discussion**
Not sure how to fix the prettier error
**Reviewers**
=> [NZPMC-106] Integrate the timer into pretty quiz interface
